/**
 * Defines the 'Abstract Syntax Tree' that will be generated by Bison.
 *
 * Here we specify all classes that will get generated when parsing
 * the input file.
 *
 * The main class is `Node`, that all other stuff inherit from.
 * It has an abstract method `outputCode()` that prints to standard
 * output the resulting Assembly from parsing each part of the code.
 */

#ifndef AST_HPP_DEFINED
#define AST_HPP_DEFINED

class Node
{
protected:
	Node* left;
	Node* right;

public:
	Node(Node* newLeft, Node* newRight)
	{
		this->left  = newLeft;
		this->right = newRight;
	}
	virtual void outputCode() = 0;
};

class NodeExpression : public Node
{
};

class NodeStatement : public Node
{
};


#endif /* AST_HPP_DEFINED */

